"""create designations table

Revision ID: 2b1295b9e9f1
Revises: 10efddd23357
Create Date: 2026-06-24 10:48:28.641163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1295b9e9f1'
down_revision: Union[str, Sequence[str], None] = '10efddd23357'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('designations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('designation_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('designation_name')
    )
    op.create_index(op.f('ix_designations_id'), 'designations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_designations_id'), table_name='designations')
    op.drop_table('designations')
    # ### end Alembic commands ###
