"""create payroll table

Revision ID: 59525e5b6bb4
Revises: 97bdd6cafc3b
Create Date: 2026-06-24 11:46:18.474588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59525e5b6bb4'
down_revision: Union[str, Sequence[str], None] = '97bdd6cafc3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payroll',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('pay_month', sa.String(length=20), nullable=False),
    sa.Column('basic_salary', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('bonus', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('deduction', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('net_salary', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payroll_id'), 'payroll', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payroll_id'), table_name='payroll')
    op.drop_table('payroll')
    # ### end Alembic commands ###
