"""create salary structures table

Revision ID: 744e0d1216b4
Revises: 7136e7c6da2f
Create Date: 2026-06-24 14:31:54.770073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '744e0d1216b4'
down_revision: Union[str, Sequence[str], None] = '7136e7c6da2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_structures',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('basic_salary', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('hra', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('allowances', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('bonus', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('deductions', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("CURRENT_TIMESTAMP"), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_salary_structures_id'), 'salary_structures', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_structures_id'), table_name='salary_structures')
    op.drop_table('salary_structures')
    # ### end Alembic commands ###
