"""add soft delete to employees

Revision ID: f0600c78a4f8
Revises: 917e8a6d0b9c
Create Date: 2026-06-24 16:50:34.290207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0600c78a4f8'
down_revision: Union[str, Sequence[str], None] = '917e8a6d0b9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'is_deleted')
    # ### end Alembic commands ###
