from .role import Role
from .user import User
from .department import Department
from .designation import Designation
from .employee import Employee
from .attendance import Attendance
from .leave_request import LeaveRequest
from .payroll import Payroll
from .category import Category
from .supplier import Supplier
from .product import Product
from .inventory import Inventory
from .customer import Customer
from .sales_order import SalesOrder