from .role import Role
from .user import User
from .department import Department
from .designation import Designation
from .employee import Employee
from .attendance import Attendance
from .leave_request import LeaveRequest
from .payroll import Payroll
from .category import Category
from .supplier import Supplier
from .product import Product
from .inventory import Inventory
from .customer import Customer
from .sales_order import SalesOrder
from .sales_order_item import SalesOrderItem
from .invoice import Invoice
from .salary_structure import SalaryStructure
from .project import Project
from .project_task import ProjectTask
from .timesheet import Timesheet
from .client import Client
from .lead import Lead
from .opportunity import Opportunity
from .ticket import Ticket
from .notification import Notification